#!/usr/bin/env bash
# Scaffold a new tenant deployment with two isolated state files
# (01-gcp-target/, 02-datasync/).
#
# Usage:
#   infra/scripts/new-aws-datasync-tenant.sh <TENANT_ID> <GCP_PROJECT_ID> [GCS_BUCKET_NAME]
#
# Example:
#   infra/scripts/new-aws-datasync-tenant.sh test-deleteme3 test-deleteme3-scowtt
#
# Defaults:
#   GCS_BUCKET_NAME defaults to "<GCP_PROJECT_ID>-crm-sync"
#   HMAC secret name is always datasync/<TENANT_ID>/gcs-hmac
#
# What it does:
#   1. Copies _template/ to <TENANT_ID>/
#   2. In each sub-stack, generates backend.hcl with a unique state key.
#   3. In each sub-stack, generates terraform.tfvars from the example with values filled in.

set -euo pipefail

usage() {
  sed -n '2,16p' "$0" | sed 's/^# \{0,1\}//'
  exit 1
}

[ $# -ge 2 ] || usage

TENANT_ID="$1"
GCP_PROJECT="$2"
GCS_BUCKET="${3:-${GCP_PROJECT}-crm-sync}"

# Validate tenant ID — must match the GCP module's regex (the stricter one).
if ! [[ "$TENANT_ID" =~ ^[a-z0-9][a-z0-9-]{1,28}[a-z0-9]$ ]]; then
  echo "ERROR: tenant_id must be 3-30 chars, lowercase alphanumeric + hyphens, start/end alphanumeric." >&2
  exit 2
fi

infra_root="$(cd "$(dirname "$0")/.." && pwd)"
template="${infra_root}/stacks/aws/datasync/tenants/_template"
dest="${infra_root}/stacks/aws/datasync/tenants/${TENANT_ID}"

if [ -e "$dest" ]; then
  echo "ERROR: ${dest} already exists. Refusing to overwrite." >&2
  exit 3
fi

cp -R "$template" "$dest"

generated_at="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

# ---------------------------------------------------------------------------
# Sub-stack 01-gcp-target
# ---------------------------------------------------------------------------

sed "s|<TENANT_ID>|${TENANT_ID}|g" \
  "${dest}/01-gcp-target/backend.hcl.example" \
  > "${dest}/01-gcp-target/backend.hcl"

cat > "${dest}/01-gcp-target/terraform.tfvars" <<EOF
# Auto-generated by infra/scripts/new-aws-datasync-tenant.sh on ${generated_at}
# Non-secret. Commit me. (HMAC values come from the GCP module at apply-time.)

tenant_id               = "${TENANT_ID}"
environment             = "dev"

gcp_project_id          = "${GCP_PROJECT}"
gcp_region              = "US"
destination_bucket_name = "${GCS_BUCKET}"
create_bucket           = true
EOF

# ---------------------------------------------------------------------------
# Sub-stack 02-datasync
# ---------------------------------------------------------------------------

sed "s|<TENANT_ID>|${TENANT_ID}|g" \
  "${dest}/02-datasync/backend.hcl.example" \
  > "${dest}/02-datasync/backend.hcl"

cat > "${dest}/02-datasync/terraform.tfvars" <<EOF
# Auto-generated by infra/scripts/new-aws-datasync-tenant.sh on ${generated_at}
# These values come from 01-gcp-target outputs after that stack has applied.

tenant_id               = "${TENANT_ID}"
environment             = "dev"

source_s3_bucket_arn    = "arn:aws:s3:::scowtt-crm-data-bucket-dev"
destination_bucket_name = "${GCS_BUCKET}"
hmac_secret_name        = "datasync/${TENANT_ID}/gcs-hmac"
EOF

# ---------------------------------------------------------------------------
# Drop the *.example files inside each sub-stack — they belong to the template only.
# (Top-level _template/ files are themselves rename-archived; per-sub-stack examples
# remain in _template but are removed from the generated tenant directory.)
# ---------------------------------------------------------------------------

rm -f \
  "${dest}/01-gcp-target/backend.hcl.example" \
  "${dest}/01-gcp-target/terraform.tfvars.example" \
  "${dest}/01-gcp-target/README.md" \
  "${dest}/02-datasync/backend.hcl.example" \
  "${dest}/02-datasync/terraform.tfvars.example" \
  "${dest}/02-datasync/README.md" \
  "${dest}/README.md"

cat <<EOF

Created infra/stacks/aws/datasync/tenants/${TENANT_ID}/
  ├── 01-gcp-target/
  │   ├── backend.hcl       (key: aws/datasync/dev/tenants/${TENANT_ID}/01-gcp-target/terraform.tfstate)
  │   └── terraform.tfvars  (tenant_id, gcp_project_id=${GCP_PROJECT}, bucket=${GCS_BUCKET})
  └── 02-datasync/
      ├── backend.hcl       (key: aws/datasync/dev/tenants/${TENANT_ID}/02-datasync/terraform.tfstate)
      └── terraform.tfvars  (tenant_id, source S3 ARN, destination bucket, hmac_secret_name)

Apply order:
  1. cd ${dest}/01-gcp-target && tofu init -backend-config=backend.hcl && tofu apply
       (creates GCS bucket + write-only SA + HMAC + AWS Secrets Manager secret)
  2. cd ${dest}/02-datasync   && tofu init -backend-config=backend.hcl && tofu apply
       (reads the secret, creates AWS DataSync task)

Then:
  git add infra/stacks/aws/datasync/tenants/${TENANT_ID}
  git commit -m "Onboard tenant ${TENANT_ID}"
  git push  # PR runs tofu-plan against the readonly role
EOF
