locals {
  name                = coalesce(var.name_prefix, "datasync-${var.tenant_id}")
  source_subdirectory = coalesce(var.source_subdirectory, "/${var.tenant_id}")

  base_tags = merge(
    {
      "tenant_id"  = var.tenant_id
      "managed-by" = "opentofu"
      "module"     = "datasync-s3-to-gcs"
    },
    var.tags,
  )
}

# ---------------------------------------------------------------------------
# Source IAM role (per spec item A.6 — "Source IAM role: autogenerated")
# DataSync assumes this role to read the source S3 bucket prefix.
# ---------------------------------------------------------------------------

data "aws_iam_policy_document" "datasync_assume" {
  statement {
    effect  = "Allow"
    actions = ["sts:AssumeRole"]

    principals {
      type        = "Service"
      identifiers = ["datasync.amazonaws.com"]
    }
  }
}

resource "aws_iam_role" "source" {
  name               = "${local.name}-source-role"
  description        = "DataSync source role for tenant ${var.tenant_id} reading ${var.source_s3_bucket_arn}"
  assume_role_policy = data.aws_iam_policy_document.datasync_assume.json
  tags               = local.base_tags
}

data "aws_iam_policy_document" "source" {
  statement {
    sid    = "ListBucket"
    effect = "Allow"
    actions = [
      "s3:GetBucketLocation",
      "s3:ListBucket",
      "s3:ListBucketMultipartUploads",
    ]
    resources = [var.source_s3_bucket_arn]

    # Scope listing to the tenant prefix only.
    condition {
      test     = "StringLike"
      variable = "s3:prefix"
      values   = ["${trimprefix(local.source_subdirectory, "/")}/*", "${trimprefix(local.source_subdirectory, "/")}"]
    }
  }

  statement {
    sid    = "ReadObjects"
    effect = "Allow"
    actions = [
      "s3:AbortMultipartUpload",
      "s3:GetObject",
      "s3:GetObjectTagging",
      "s3:GetObjectVersion",
      "s3:GetObjectVersionTagging",
      "s3:ListMultipartUploadParts",
    ]
    resources = ["${var.source_s3_bucket_arn}${local.source_subdirectory}/*"]
  }
}

resource "aws_iam_role_policy" "source" {
  name   = "${local.name}-source-policy"
  role   = aws_iam_role.source.id
  policy = data.aws_iam_policy_document.source.json
}

# ---------------------------------------------------------------------------
# CloudWatch log group (DataSync task logs)
# ---------------------------------------------------------------------------

resource "aws_cloudwatch_log_group" "task" {
  name              = "/aws/datasync/${local.name}"
  retention_in_days = var.log_retention_days
  tags              = local.base_tags
}

data "aws_iam_policy_document" "log_resource_policy" {
  statement {
    sid    = "DataSyncLogsToCloudWatch"
    effect = "Allow"
    actions = [
      "logs:PutLogEvents",
      "logs:CreateLogStream",
    ]
    resources = ["${aws_cloudwatch_log_group.task.arn}:*"]

    principals {
      type        = "Service"
      identifiers = ["datasync.amazonaws.com"]
    }
  }
}

resource "aws_cloudwatch_log_resource_policy" "task" {
  policy_name     = "${local.name}-datasync-logs"
  policy_document = data.aws_iam_policy_document.log_resource_policy.json
}

# ---------------------------------------------------------------------------
# Source location — S3
# ---------------------------------------------------------------------------

resource "aws_datasync_location_s3" "source" {
  s3_bucket_arn = var.source_s3_bucket_arn
  subdirectory  = local.source_subdirectory

  s3_config {
    bucket_access_role_arn = aws_iam_role.source.arn
  }

  tags = merge(local.base_tags, { "datasync-role" = "source" })

  depends_on = [aws_iam_role_policy.source]
}

# ---------------------------------------------------------------------------
# Destination location — GCS via S3 interoperability (HMAC)
# ---------------------------------------------------------------------------

resource "aws_datasync_location_object_storage" "destination" {
  server_hostname = var.gcs_interop_endpoint
  server_protocol = "HTTPS"
  server_port     = 443

  bucket_name  = var.destination_bucket_name
  subdirectory = var.destination_subdirectory

  access_key  = var.gcs_hmac_access_key_id
  secret_key  = var.gcs_hmac_secret_access_key
  agent_arns  = var.agent_arns

  tags = merge(local.base_tags, { "datasync-role" = "destination" })
}

# ---------------------------------------------------------------------------
# Task — ENHANCED mode, hourly schedule
# ---------------------------------------------------------------------------

resource "aws_datasync_task" "this" {
  name                     = local.name
  source_location_arn      = aws_datasync_location_s3.source.arn
  destination_location_arn = aws_datasync_location_object_storage.destination.arn
  task_mode                = var.task_mode
  cloudwatch_log_group_arn = aws_cloudwatch_log_group.task.arn

  schedule {
    schedule_expression = var.schedule_expression
  }

  options {
    log_level                = "TRANSFER"
    verify_mode              = "ONLY_FILES_TRANSFERRED"
    overwrite_mode           = "ALWAYS"
    preserve_deleted_files   = "PRESERVE"
    posix_permissions        = "NONE"
    uid                      = "NONE"
    gid                      = "NONE"
    atime                    = "NONE"
    mtime                    = "NONE"
    task_queueing            = "ENABLED"
    transfer_mode            = "CHANGED"
    bytes_per_second         = -1
  }

  tags = local.base_tags

  depends_on = [aws_cloudwatch_log_resource_policy.task]
}
